# Generated by Django 5.1.4 on 2025-03-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0002_pythontopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythontopic',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='pythontopic',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythontopic',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythontopic',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythontopic',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pythontopic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
