# Generated by Django 5.1.4 on 2025-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0003_rename_content_pythontopic_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Java topic', max_length=100)),
                ('sub_java_1', models.CharField(blank=True, default='', help_text='Subtopic 1', max_length=150)),
                ('sub_java_2', models.TextField(blank=True, help_text='Subtopic 2')),
                ('sub_java_3', models.TextField(blank=True, help_text='Subtopic 3')),
                ('sub_java_4', models.TextField(blank=True, help_text='Subtopic 4')),
                ('sub_java_5', models.TextField(blank=True, help_text='Subtopic 5')),
            ],
            options={
                'verbose_name': 'Java Topic',
                'verbose_name_plural': 'Java Topics',
            },
        ),
    ]
