# Generated by Django 5.1.4 on 2025-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0004_javatopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javatopic',
            options={},
        ),
        migrations.RemoveField(
            model_name='javatopic',
            name='sub_java_1',
        ),
        migrations.RemoveField(
            model_name='javatopic',
            name='sub_java_2',
        ),
        migrations.RemoveField(
            model_name='javatopic',
            name='sub_java_3',
        ),
        migrations.RemoveField(
            model_name='javatopic',
            name='sub_java_4',
        ),
        migrations.RemoveField(
            model_name='javatopic',
            name='sub_java_5',
        ),
        migrations.AddField(
            model_name='javatopic',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javatopic',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javatopic',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javatopic',
            name='content5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javatopic',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='javatopic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
