# Generated by Django 5.1.4 on 2025-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0005_alter_javatopic_options_remove_javatopic_sub_java_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='javatopic',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='javatopic',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='javatopic',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
