# Generated by Django 5.1.4 on 2025-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0006_javatopic_content1_alter_javatopic_subtitle1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('HTML1', models.CharField(blank=True, max_length=200, null=True)),
                ('HTML2', models.TextField(blank=True, null=True)),
                ('HTML3', models.TextField(blank=True, null=True)),
                ('HTML4', models.TextField(blank=True, null=True)),
                ('HTML5', models.TextField(blank=True, null=True)),
                ('HTML6', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
