# Generated by Django 5.1.4 on 2025-03-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0008_htmltopic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmltopic',
            name='image',
        ),
    ]
