# Generated by Django 5.1.4 on 2025-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebapp', '0009_remove_htmltopic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltopic',
            name='HTML2',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='htmltopic',
            name='HTML3',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='htmltopic',
            name='HTML4',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='htmltopic',
            name='HTML5',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='htmltopic',
            name='HTML6',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
